[package]
name = "websocket"
version = "0.1.0"
edition = "2024"

[dependencies]
socketioxide = "*"
axum = "*"
tokio = { version = "*", features = ["rt", "rt-multi-thread", "macros"] }
redis = "0.26.1"
serde_json = "1.0.142"